# Generated by Django 4.2.13 on 2024-05-10 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anlam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anlam_sira', models.IntegerField()),
                ('anlam', models.TextField()),
                ('fiil', models.IntegerField()),
                ('gos', models.IntegerField()),
                ('tipkes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Atasozu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madde', models.TextField()),
                ('on_taki', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Madde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anlam_gor', models.IntegerField()),
                ('anlam_say', models.IntegerField()),
                ('birlesikler', models.TextField()),
                ('cesit_say', models.IntegerField()),
                ('cesit', models.TextField()),
                ('cogul_mu', models.IntegerField()),
                ('egik_mi', models.IntegerField()),
                ('font', models.TextField()),
                ('gosterim_tarihi', models.IntegerField()),
                ('kac', models.IntegerField()),
                ('kelime_no', models.IntegerField()),
                ('lisan_kodu', models.IntegerField()),
                ('lisan', models.TextField()),
                ('madde_duz', models.TextField()),
                ('madde', models.TextField()),
                ('on_taki', models.TextField()),
                ('ozel_mi', models.IntegerField()),
                ('taki', models.TextField()),
                ('telaffuz', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ozellik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekno', models.IntegerField()),
                ('kisa_adi', models.TextField()),
                ('tam_adi', models.TextField()),
                ('tur', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Yazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekno', models.IntegerField()),
                ('kisa_adi', models.TextField()),
                ('tam_adi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ornek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kac', models.IntegerField()),
                ('ornek_sira', models.IntegerField()),
                ('ornek', models.TextField()),
                ('yazar_vd', models.TextField()),
                ('anlam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vortaro.anlam')),
                ('yazar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vortaro.yazar')),
            ],
        ),
        migrations.CreateModel(
            name='Madde_atasozu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atasozu_madde_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vortaro.atasozu')),
                ('madde_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vortaro.madde')),
            ],
        ),
        migrations.AddField(
            model_name='atasozu',
            name='madde_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vortaro.madde'),
        ),
        migrations.CreateModel(
            name='Anlam_ozellik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anlam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vortaro.anlam')),
                ('ozellik_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vortaro.ozellik')),
            ],
        ),
        migrations.AddField(
            model_name='anlam',
            name='madde_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vortaro.madde'),
        ),
    ]
