# Generated by Django 4.2.13 on 2024-05-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortaro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnlamOzellik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'anlam_ozellik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaddeAtasozu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'madde_atasozu',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='madde_atasozu',
            name='atasozu_madde_id',
        ),
        migrations.RemoveField(
            model_name='madde_atasozu',
            name='madde_id',
        ),
        migrations.AlterModelOptions(
            name='anlam',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='atasozu',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='madde',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ornek',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ozellik',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='yazar',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Anlam_ozellik',
        ),
        migrations.DeleteModel(
            name='Madde_atasozu',
        ),
    ]
